pipeline {
    agent any

    tools {
        nodejs "NodeJS"
    }

    stages {

        stage("Install Environment") {
            steps {
                dir('tripweaver') {
                    echo 'Installing Environment'
                    sh 'npm install -g pnpm'
                    sh 'pnpm install'
                }
            }
        }

        stage("Test Build") {
            steps {
                dir('tripweaver') {
                    echo 'Test Build'
                    sh 'pnpm run build'
                }
            }
        }

        stage("Clear Running Docker Containers") {
            steps {
                script {
                    def containerIds = sh(script: 'docker ps -a --filter "ancestor=tripweaver-image" -q', returnStdout: true).trim()

                    if (containerIds) {
                        sh "docker stop ${containerIds}"
                        sh "docker rm ${containerIds}"
                    } else {
                        echo "No containers with the image 'tripweaver-image' found."
                    }
                }
            }
        }

        stage("Remove Old Docker Images") {
            steps {
                script {
                    def imageIds = sh(script: 'docker images --filter "reference=tripweaver-image" -q', returnStdout: true).trim()

                    if (imageIds) {
                        sh "docker rmi ${imageIds}"
                    } else {
                        echo "No images with the name 'tripweaver-image' found."
                    }
                }
            }
        }

        stage("Prepare Backend Environment"){
            steps {
                dir('tripweaver') {
                    echo 'Create .env file'
                    script {
                    sh 'touch .env'
                    sh '''
                    echo "MONGDB_URI=${MONGDB_URI}" >> .env
                    '''
                    }
                }
            }
        }

        stage("Deploy on Docker"){
            steps {
                dir('tripweaver') {
                    echo 'Deploy TripWeaver on Docker'
                    sh 'docker build -t tripweaver-image .'
                    sh 'docker run -d -p 3000:3000 -e TZ="Asia/Bangkok" tripweaver-image'
                }
            }
        }
    }
}